name: Red-Black Tree Driver CI

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

  workflow_dispatch:

jobs:
  build-and-test:
    name: ${{ matrix.os }} / ${{ matrix.build_type }}

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          # - macos-latest

        build_type:
          - Debug
          - Release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Show tool versions
        run: |
          cmake --version
          ctest --version

      - name: Configure
        run: >
          cmake
          -S .
          -B build
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DKVDB_ENABLE_TESTS=ON
          -DKVDB_ENABLE_ASAN=OFF
          -DKVDB_ENABLE_UBSAN=OFF
          -DKVDB_DRIVER=RBTREE

      - name: Build
        run: >
          cmake
          --build build
          --config ${{ matrix.build_type }}
          # --parallel

      - name: Run tests
        run: >
          ctest
          --test-dir build
          --build-config ${{ matrix.build_type }}
          --output-on-failure
          --no-tests=error

  sanitizer-test:
    name: ${{ matrix.os }} / ${{ matrix.build_type }} / ASan + UBSan

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os:
          - ubuntu-latest

        build_type:
          - Debug
          - Release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Configure
        run: >
          cmake
          -S .
          -B build-sanitized
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DKVDB_ENABLE_TESTS=ON
          -DKVDB_ENABLE_ASAN=ON
          -DKVDB_ENABLE_UBSAN=ON
          -DKVDB_DRIVER=RBTREE

      - name: Build
        run: >
          cmake
          --build build-sanitized
          --config ${{ matrix.build_type }}

      - name: Run tests
        run: >
          ctest
          --test-dir build-sanitized
          --build-config ${{ matrix.build_type }}
          --output-on-failure
          --no-tests=error